# Generated by codegen plugin

import re
from playwright.sync_api import Playwright, sync_playwright, expect

def run(playwright: Playwright) -> None:
    browser = playwright.webkit.launch(headless=False, slow_mo=1000)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://aquabottesting.com/index.html")
    page.get_by_role("link", name="Forms").click()
    page.get_by_role("textbox", name="Name").click()
    page.get_by_role("textbox", name="Name").fill(" SK")
    page.get_by_role("textbox", name="Name").press("Tab")
    page.get_by_role("textbox", name="Email").fill("skk@example.com")
    page.get_by_role("textbox", name="Email").press("Tab")
    page.get_by_role("textbox", name="Phone").fill("8898998")
    page.get_by_text("Mobile Phone").click()
    page.get_by_role("textbox", name="Your message").click()
    page.get_by_role("textbox", name="Your message").fill("Wanted to learn playwright")
    page.locator("#cselect").select_option("Frameworks")
    page.locator("#cerror").check()
    page.get_by_role("button", name="SUBMIT").click()
    page.get_by_text("Message Failed!").click()
    expect(page.locator("#cmsgSubmit")).to_contain_text("Message Failed!")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)